name: "Create releases"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build application 
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install linux dependencies
        run: sudo apt-get install fuse libfuse2 libopengl0 libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      # - name: Set version
      #   run: |
      #     npm version --no-git-tag-version from-git
      - name: Apply packer patch (upgrade linuxqtdeploy to continuous)
        run: |
          npm run patch
      - name: Build application
        run: |
          npm run build
      - name: Package application
        run: |
          echo $VERSION
          npm run package
        env:
          VERSION: ${{ github.event.release.tag_name }}
      # - name: Upload release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ needs.release.outputs.upload_url }}
      #     asset_path: ./${{ matrix.asset_name }}.tar.gz
      #     asset_name: ${{ matrix.asset_name }}.tar.gz
      #     asset_content_type: application/gzip 