name: "Create releases"

# on:
#   push:
#     tags:
#       - '*'

on:
  push

jobs:
  build:
    name: Build application 
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      # - name: Set version
      #   run: |
      #     npm version --no-git-tag-version from-git
      - name: Build application
        run: |
          npm run build
      - name: Package application
        run: npm run package