name: "Create release"

on:
  release:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/download-artifact@v3
      with:
        name: DeadbrainWallet-${{ github.ref_name }}-x86_64.AppImage
        path: build