name: "Run tests"

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3
    - name: Run tests
      run: npm test